name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install -y openssl libssl-dev
    - name: Compile project
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: artifacts
        path: main
        if-no-files-found: warn
